# Generated by Django 5.0.1 on 2024-02-02 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='locai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereço', models.TextField(max_length=1000)),
                ('email', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='local',
        ),
    ]
