# Generated by Django 5.0.1 on 2024-03-14 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resultado', '0002_locai_delete_local'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locai',
            old_name='endereço',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='locai',
            old_name='email',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='locai',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='locai',
            old_name='telefone',
            new_name='number',
        ),
    ]
